### ISSUE TITLE
VenksSurvival not loading

### ISSUE THREAD

**Issue by popdynamite5511** [ddinan/classicube-stuff#24]
VenksSurvival is not loading on a VPS that I am using.
The error is the following:
!!!Error (Could not find a part of the path "/home/container/plugins/VenksSurvival/config.properties".) - See logs/errors/2022-09-06error.log for more details
Config.properties was not automatically created so I manually did that, but it still says this

**Comment by ddinan** [comment]
The curse of the lazy developer strikes again, alas, as I have yet to add automatic file generation upon startup. Creating the files manually should work, assuming the correct path and file name was provided. Check to see if there is a typo in either the folder or file names. They are case-sensitive so something like **Config.properties** should be **config.properties**.

**Comment by ddinan** [comment]
Closing this as it was fixed a while ago,
