### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by DeathDeaglesYT** [ddinan/classicube-stuff#26]
When i type /pcompile or /compile in-game, it says this command does not exist, use /client to see all available commands. Anyone know how to do this? im new to this btw so go easy on me.

**Comment by ddinan** [comment]
This is for the MCGalaxy server software, not the ClassiCube client. Please check the [installation guide](https://github.com/ddinan/classicube-stuff#installation) for more information on how to set up plugins.
